run:
  timeout: 3m
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - gofumpt
    # revive and errcheck disabled to keep CLI glue concise
    # - revive
    # - errcheck
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: package-comments
        disabled: true
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
